Added various file formats to constants.py
TagStudioDev/TagStudio pull request #231
Opened 2024-05-31 18:27 UTC by PossiblePanda

I added various file formats to the constants.py file, including ".dmg", ".s7z", ".cr2", ".jar", ".msi"

2024-05-31 18:31 UTC, PossiblePanda commented
I just now realize that some of my additions are debatable, such as .jar could also be an archive file

2024-06-03 06:04 UTC, CyanVoxel commented
".cr2" would be valuable to have, however both the `ARCHIVE_TYPES` and `PROGRAM_TYPES` lists aren't currently being used anywhere. There will be a shift towards using [MIME types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types) in favor of these hardcoded lists in the future, however in the meantime it would probably be good to have at least the ".cr2" and ".s7z" extensions added. You're right with the ".jar" ambiguity, in addition to ".dmg" being more closely a disk image type and ".msi" also being in a nebulous space between a program and specifically an installer.

2024-06-03 22:47 UTC, CyanVoxel requested changes

2024-06-03 22:47 UTC, CyanVoxel commented on tagstudio/src/core/constants.py
> +RAW_IMAGE_TYPES: list[str] = [".raw", ".dng", ".rw2", ".nef", ".arw", ".crw", ".cr3", ".cr2"]
Ruff formatting
```suggestion
RAW_IMAGE_TYPES: list[str] = [
    ".raw",
    ".dng",
    ".rw2",
    ".nef",
    ".arw",
    ".crw",
    ".cr2",
    ".cr3",
]
```

2024-06-03 22:47 UTC, CyanVoxel commented on tagstudio/src/core/constants.py
> +PROGRAM_TYPES: list[str] = [".exe", ".app", ".jar", ".msi"]
Mentioned changes + Ruff formatting
```suggestion
ARCHIVE_TYPES: list[str] = [
    ".zip",
    ".rar",
    ".tar",
    ".tar",
    ".gz",
    ".tgz",
    ".7z",
    ".s7z",
]
PROGRAM_TYPES: list[str] = [".exe", ".app"]
```

2024-06-04 21:07 UTC, PossiblePanda commented
I think I accepted your commits correctly @CyanVoxel , not the best at doing PR's though so let me know if I did it wrong xD

2024-06-04 21:13 UTC, CyanVoxel commented
> I think I accepted your commits correctly @CyanVoxel , not the best at doing PR's though so let me know if I did it wrong xD

You did excellent! And now you've got some more PR practice for the future 😉
Thank you for your work on this!

2024-06-04 21:13 UTC, CyanVoxel approved these changes

2024-06-04 21:13 UTC, merged