Change "show file in explorer" to be different depending on the OS
TagStudioDev/TagStudio pull request #370
Opened 2024-08-23 01:00 UTC by SupKittyMeow

Windows says explorer, Mac says Finder, and Linux just says filesystem (as I don't know what it is on Linux)

2024-08-23 03:07 UTC, CyanVoxel requested changes
Adding to my Linux file manager comment, I would suggest putting the Linux case last in the if-else chain and instead have Windows as the middle case since both Windows and macOS have expected file explorer names, while for Linux + any other case we can use a generic catch-all term.

Also, are you able to use [Ruff](https://github.com/TagStudioDev/TagStudio/blob/main/CONTRIBUTING.md#ruff) for linting or would you need some help with that?

2024-08-23 03:20 UTC, SupKittyMeow commented
> Adding to my Linux file manager comment, I would suggest putting the Linux case last in the if-else chain and instead have Windows as the middle case since both Windows and macOS have expected file explorer names, while for Linux + any other case we can use a generic catch-all term.
> 
> Also, are you able to use [Ruff](https://github.com/TagStudioDev/TagStudio/blob/main/CONTRIBUTING.md#ruff) for linting or would you need some help with that?

That should be fixed now. I haven't ever used Linux, but yeah I've heard that there's multiple file managers somewhere.

I've never actually heard of Ruff, so I probably need help on that, but I'll also look into it.

2024-08-23 03:45 UTC, SupKittyMeow commented
Would these be better? I solved most of the Ruff errors:
video_player.py:
`# Licensed under the GPL-3.0 License.
# Created for TagStudio: https://github.com/CyanVoxel/TagStudio

import logging

import platform
import typing

from PySide6.QtCore import (
    Qt,
    QSize,
    QTimer,
    QVariantAnimation,
    QUrl,
    QObject,
    QEvent,
    QRectF,
)
from PySide6.QtMultimedia import QMediaPlayer, QAudioOutput, QMediaDevices
from PySide6.QtMultimediaWidgets import QGraphicsVideoItem
from PySide6.QtWidgets import QGraphicsView, QGraphicsScene
from PySide6.QtGui import (
    QPen,
    QColor,
    QBrush,
    QResizeEvent,
    QWheelEvent,
    QAction,
    QRegion,
    QBitmap,
)
from PySide6.QtSvgWidgets import QSvgWidget
from src.qt.helpers.file_opener import FileOpenerHelper
from PIL import Image, ImageDraw
from src.core.enums import SettingItems

if typing.TYPE_CHECKING:
    from src.qt.ts_qt import QtDriver


class VideoPlayer(QGraphicsView):
    """A basic video player."""

    video_preview = None
    play_pause = None
    mute_button = None

    def __init__(self, driver: "QtDriver") -> None:
        super().__init__()
        self.driver = driver
        self.resolution = QSize(1280, 720)
        self.animation = QVariantAnimation(self)
        self.animation.valueChanged.connect(
            lambda value: self.setTintTransparency(value)
        )
        self.hover_fix_timer = QTimer()
        self.hover_fix_timer.timeout.connect(lambda: self.checkIfStillHovered())
        self.hover_fix_timer.setSingleShot(True)
        self.content_visible = False
        self.filepath = None

        # Set up the video player.
        self.installEventFilter(self)
        self.setScene(QGraphicsScene(self))
        self.player = QMediaPlayer(self)
        self.player.mediaStatusChanged.connect(
            lambda: self.checkMediaStatus(self.player.mediaStatus())
        )
        self.video_preview = VideoPreview()
        self.player.setVideoOutput(self.video_preview)
        self.video_preview.setAcceptHoverEvents(True)
        self.video_preview.setAcceptedMouseButtons(Qt.MouseButton.RightButton)
        self.video_preview.installEventFilter(self)
        self.player.setAudioOutput(
            QAudioOutput(QMediaDevices().defaultAudioOutput(), self.player)
        )
        self.player.audioOutput().setMuted(True)
        self.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scene().addItem(self.video_preview)
        self.video_preview.setAcceptedMouseButtons(Qt.MouseButton.LeftButton)

        # Set up the video tint.
        self.video_tint = self.scene().addRect(
            0,
            0,
            self.video_preview.size().width(),
            self.video_preview.size().height(),
            QPen(QColor(0, 0, 0, 0)),
            QBrush(QColor(0, 0, 0, 0)),
        )

        # Set up the buttons.
        self.play_pause = QSvgWidget()
        self.play_pause.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground, True)
        self.play_pause.setMouseTracking(True)
        self.play_pause.installEventFilter(self)
        self.scene().addWidget(self.play_pause)
        self.play_pause.resize(72, 72)
        self.play_pause.move(
            int(self.width() / 2 - self.play_pause.size().width() / 2),
            int(self.height() / 2 - self.play_pause.size().height() / 2),
        )
        self.play_pause.hide()

        self.mute_button = QSvgWidget()
        self.mute_button.setAttribute(Qt.WidgetAttribute.WA_TranslucentBackground, True)
        self.mute_button.setMouseTracking(True)
        self.mute_button.installEventFilter(self)
        self.scene().addWidget(self.mute_button)
        self.mute_button.resize(32, 32)
        self.mute_button.move(
            int(self.width() - self.mute_button.size().width() / 2),
            int(self.height() - self.mute_button.size().height() / 2),
        )
        self.mute_button.hide()

        self.setContextMenuPolicy(Qt.ContextMenuPolicy.ActionsContextMenu)
        self.opener = FileOpenerHelper(filepath=self.filepath)
        autoplay_action = QAction("Autoplay", self)
        autoplay_action.setCheckable(True)
        self.addAction(autoplay_action)
        autoplay_action.setChecked(
            self.driver.settings.value(SettingItems.AUTOPLAY, True, bool)  # type: ignore
        )
        autoplay_action.triggered.connect(lambda: self.toggleAutoplay())
        self.autoplay = autoplay_action

        open_file_action = QAction("Open file", self)
        open_file_action.triggered.connect(self.opener.open_file)

        system = platform.system()
        if system == "Darwin":
            open_explorer_action = QAction("Reveal in Finder", self)
        elif system == "Windows":
            open_explorer_action = QAction("Open in Explorer", self)
        else:
            open_explorer_action = QAction("Open in explorer", self)

        open_explorer_action.triggered.connect(self.opener.open_explorer)
        self.addAction(open_file_action)
        self.addAction(open_explorer_action)

    def close(self, *args, **kwargs) -> None:
        self.player.stop()
        super().close(*args, **kwargs)

    def toggleAutoplay(self) -> None:
        self.driver.settings.setValue(SettingItems.AUTOPLAY, self.autoplay.isChecked())
        self.driver.settings.sync()

    def checkMediaStatus(self, media_status: QMediaPlayer.MediaStatus) -> None:
        if media_status == QMediaPlayer.MediaStatus.EndOfMedia:
            # Switches current video to with video at filepath.
            # Reason for this is because Pyside6 can't handle setting a new source and freezes.
            # Even if I stop the player before switching, it breaks.
            # On the plus side, this adds infinite looping for the video preview.
            self.player.stop()
            self.player.setSource(QUrl().fromLocalFile(self.filepath))
            self.player.setPosition(0)
            if self.autoplay.isChecked():
                self.player.play()
            else:
                self.player.pause()
            self.opener.set_filepath(self.filepath)
            self.keepControlsInPlace()
        self.updateControls()

    def updateControls(self) -> None:
        if self.player.audioOutput().isMuted():
            self.mute_button.load(self.driver.rm.volume_mute_icon)
        else:
            self.mute_button.load(self.driver.rm.volume_icon)

        if self.player.isPlaying():
            self.play_pause.load(self.driver.rm.pause_icon)
        else:
            self.play_pause.load(self.driver.rm.play_icon)

    def wheelEvent(self, event: QWheelEvent) -> None:
        return

    def eventFilter(self, obj: QObject, event: QEvent) -> bool:
        # This chunk of code is for the video controls.
        if (
            obj == self.play_pause
            and event.type() == QEvent.Type.MouseButtonPress
            and event.button() == Qt.MouseButton.LeftButton  # type: ignore
        ):
            if self.player.hasVideo():
                self.pauseToggle()

        if (
            obj == self.mute_button
            and event.type() == QEvent.Type.MouseButtonPress
            and event.button() == Qt.MouseButton.LeftButton  # type: ignore
        ):
            if self.player.hasAudio():
                self.muteToggle()

        if (
            obj == self.video_preview
            and event.type() == QEvent.Type.GraphicsSceneHoverEnter
            or event.type() == QEvent.Type.HoverEnter
        ):
            if self.video_preview.isUnderMouse():
                self.underMouse()
                self.hover_fix_timer.start(10)
        elif (
            obj == self.video_preview
            and event.type() == QEvent.Type.GraphicsSceneHoverLeave
            or event.type() == QEvent.Type.HoverLeave
        ):
            if not self.video_pr [...]

2024-08-24 07:17 UTC, CyanVoxel commented
In addition to the Ruff formatting it looks like MyPy is failing due to `open_explorer_action` being defined inside of the if-else blocks and the app run test is failing due to a mismatch between `open_file_action` and `open_explorer_action`

2024-08-25 02:20 UTC, SupKittyMeow commented
> In addition to the Ruff formatting it looks like MyPy is failing due to `open_explorer_action` being defined inside of the if-else blocks and the app run test is failing due to a mismatch between `open_file_action` and `open_explorer_action`

Should be fixed now.

2024-08-25 02:48 UTC, CyanVoxel commented
af4c0d1547b0feddb6695d7f05a34c827dce3e5c is now trying to do a lot of additional things

2024-08-25 04:58 UTC, SupKittyMeow commented
> [af4c0d1](https://github.com/TagStudioDev/TagStudio/commit/af4c0d1547b0feddb6695d7f05a34c827dce3e5c) is now trying to do a lot of additional things

oh i did that because of all of the Ruff warnings

2024-08-25 05:13 UTC, CyanVoxel commented
> oh i did that because of all of the Ruff warnings

Ruff provides additional lint suggestions in addition to what it's configured to format when run, either locally or though the workflow check. Using `ruff format` as described in the [CONTRIBUTING.md](https://github.com/TagStudioDev/TagStudio/blob/main/CONTRIBUTING.md#ruff) would've fixed the issues the check was failing on. Now there are several additional changes that are out of the scope of this PR - I would just revert your changes made in af4c0d1547b0feddb6695d7f05a34c827dce3e5c (please use more descriptive commit names than "thing" in the future) and run `ruff format` while leaving the other lint suggestions alone.

2024-08-25 05:28 UTC, SupKittyMeow commented
> > oh i did that because of all of the Ruff warnings
> 
> Ruff provides additional lint suggestions in addition to what it's configured to format when run, either locally or though the workflow check. Using `ruff format` as described in the [CONTRIBUTING.md](https://github.com/TagStudioDev/TagStudio/blob/main/CONTRIBUTING.md#ruff) would've fixed the issues the check was failing on. Now there are several additional changes that are out of the scope of this PR - I would just revert your changes made in [af4c0d1](https://github.com/TagStudioDev/TagStudio/commit/af4c0d1547b0feddb6695d7f05a34c827dce3e5c) (please use more descriptive commit names than "thing" in the future) and run `ruff format` while leaving the other lint suggestions alone.

Oh ok will do rn

2024-08-25 05:40 UTC, SupKittyMeow commented
Should be good now.

2024-08-25 05:52 UTC, SupKittyMeow commented
I forgot about something but now it should work.

2024-08-25 06:07 UTC, CyanVoxel approved these changes
Seems to be all good now! Thank you for working on this. I'll mark this as mergeable, but I'll still need to determine if this is better suited for the `Alpha-v9.4` or post-#332 `main` branches. Nothing you need to worry about though - if I need to rebase I'll take care of that before pulling.

2024-08-31 23:47 UTC, merged