More ways to open files
TagStudioDev/TagStudio pull request #455
Opened 2024-09-06 00:35 UTC by Tyrannicodin

Adds both double click functionality to thumbnails in the thumbnail grid and an open files shortcut `ctrl+shift+O`.

2024-09-09 17:10 UTC, yedpodtrzitko commented
Double click makes sense, but `Ctrl+Shift+O` feels very unusual. Maybe it's because I'm on macOS where the convention is `Cmd`+`↓`  (`ControlModifier` + `Key.Key_Down`). Using this combo here would make it feel right.

2024-09-12 00:13 UTC, CyanVoxel commented
TIL that [Command-Down Arrow](https://support.apple.com/en-us/102650) opens the selected item in Finder. If there was an equivalent shortcut for Windows Explorer I would've recommended to use each on their respective platforms, but I can't seem to find one.

2024-09-12 00:45 UTC, CyanVoxel requested changes
In your description you say that you've added double-clicking to open files, however I don't see anything in the code ~~or in practice that would suggest that.~~

EDIT: I'm now able to see what the extra click connection was supposed to do, however I would not call this "double-click" to open. Every additional click opens the file an additional time, so triple-clicking the file opens it twice, quadruple-clicking opens it three times, and so on. This also triggers when you make a multi-file selection then return to click the original file with the intention of resetting the selection back to that file. Finally it also seems to break as soon as you interact with the program a bit by searching, which is why I did not see any of this behavior initially.

This may be due to some other changes since #332, but it could also be related to the fact that the connection here is never disconnected. `item_thumb` has the `update_clickable` method that's used to do exactly this, where it disconnects the previous clickable and gets assigned a new one. I would recommend mirroring this for the double-click connection.

I would also expect Ctrl/Command + Down Arrow to open *all* the selected files, however I understand that this was not even a context menu option previously and would likely require additional refactoring (Plus it seems there's now a bug where Ctrl+Click selecting does not update the preview panel).

2024-09-12 00:45 UTC, CyanVoxel commented on tagstudio/src/qt/widgets/item_thumb.py
> +        )
What is this supposed to be doing? Removing it doesn't change any functionality

2024-09-12 02:06 UTC, yedpodtrzitko commented
> TIL that [Command-Down Arrow](https://support.apple.com/en-us/102650) opens the selected item in Finder. If there was an equivalent shortcut for Windows Explorer I would've recommended to use each on their respective platforms, but I can't seem to find one.

on Windows it's just Enter, no?

2024-09-12 02:10 UTC, CyanVoxel commented
> > TIL that [Command-Down Arrow](https://support.apple.com/en-us/102650) opens the selected item in Finder. If there was an equivalent shortcut for Windows Explorer I would've recommended to use each on their respective platforms, but I can't seem to find one.
> 
> on Windows it's just Enter, no?

Apparently it is... So simple that Microsoft doesn't even consider it a "[shortcut](https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec)"

2024-09-17 01:02 UTC, yedpodtrzitko requested changes

2024-09-19 02:21 UTC, yedpodtrzitko commented
please fix the pipeline, thanks.

2024-09-21 15:45 UTC, yedpodtrzitko approved these changes

2024-12-10 22:06 UTC, roboticforest commented
> In this case I would recommend using the default behavior for each major OS's native file manager (macOS and Windows in this case, with a fallback on one for Linux unless someone can provide more information on that).

Linux file browsers work just like Windows, or at least every version of Ubuntu, Mint, and old versions of RedHat that I've used. The file browsers let you navigate with arrow keys, or by typing the name of the file, then you can just press enter to open what's selected. Or, double-click, of course.

2025-03-12 07:06 UTC, CyanVoxel commented
Thank you for your work on this! I apologize for not getting it pulled previously, I was anticipating the platform specific shortcuts to be changed in the background while tending to other high priority areas of the project.

What I've done now is port and update this functionality to a new PR (#858) with a co-author commit that brings over all of the changes added here along with the last bit of review feedback and updates to bring it up to the current codebase standards (translations, formatting, changed imports, etc.). I also have plans to extend some of the functionality here to other areas of the project, such as adding the double-click to the preview panel.

Thank you again for your previous work on this, and I hope you're doing well!

2025-03-12 07:06 UTC, closed without merging