Fix tag search to not require wildcards
TagStudioDev/TagStudio pull request #481
Opened 2024-09-09 19:43 UTC by Tyrannicodin

Previously, searching for tags required % wildcards to be added either side in order to search for a tag without an exact match, however this removes that requirement.

2024-09-09 23:38 UTC, yedpodtrzitko commented
please add a test for this scenario, so there wont be any regression in future, thanks.

2024-09-11 14:01 UTC, yedpodtrzitko requested changes
please add a test for this scenario, so there wont be any regression in future, thanks.

2024-09-12 02:10 UTC, yedpodtrzitko approved these changes

2024-09-12 02:23 UTC, CyanVoxel commented
Mergeable once the Ruff error is addressed

2024-09-12 22:02 UTC, merged